# Spring Boot Application Properties
spring.application.name=EmployeeManagementSystem

# Primary Data Source Configurations (H2 database)
app.datasource.primary.jdbc-url=jdbc:h2:mem:primarydb;DB_CLOSE_DELAY=-1
app.datasource.primary.username=sa
app.datasource.primary.password=password
app.datasource.primary.driver-class-name=org.h2.Driver

# Secondary Data Source Configurations (For audit logs)
app.datasource.secondary.jdbc-url=jdbc:h2:mem:secondarydb;DB_CLOSE_DELAY=-1
app.datasource.secondary.username=sa
app.datasource.secondary.password=password
app.datasource.secondary.driver-class-name=org.h2.Driver

# JPA and Hibernate configurations
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Batch Processing Configuration (Exercise 10)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# H2 Console configuration (for debugging purposes)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
